name: GitHub Profile Summary Cards

on:
  schedule:
    - cron: "0 */24 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-summary-cards
    steps:
      - uses: actions/checkout@v4
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: zaidbharde
          BRANCH_NAME: main
          theme: github_dark
          title_color: D4AF37
          text_color: E7E1D6
          bg_color: 0B0709
          border_color: 3A2A22
          icon_color: D93A50
          chart_color: D4AF37
